name: "Jinja2 Portfolio Generator Docker"
description: "Generates a portfolio HTML from GitHub repos using Python and Tailwind and deploys to GitHub Pages"

runs:
  using: "docker"
  image: "Dockerfile"
  args: []
